steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/assignment/ivan-frontend', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/assignment/ivan-frontend']
logsBucket: 'gs://assignment'